### ISSUE TITLE
.png 이슈 확인 후 답변

### ISSUE THREAD

**Issue by HAERUHAERU** [ZCube/ACTWebSocket#22]
1.3.3.7 버전으로 확인해보니 아이콘이 잘 표시되는 것 같습니다. 기존과 달리 오버레이 크기 조절 화살표가 최초 화면에서는 안 뜨는게 좀 의아하긴한데 이 부분은 제가 새로 짜면서 정리해보면 될 것 같긴 해요!

그런데 lastest 버전은 여전히 아이콘이 표시되지 않네요. 해외 유저들에게는 릴리즈 링크로 배포해서 1.3.3.7 이상으로 다운로드할 수 있게 권고하겠습니다!

웹소켓 배포가 많이 되어 해외에서도 웹소켓 호환 스킨이 생기기도 했고 저도 이번에 BeforeLogLineRead를 활용해서 로그 분석기도 만들어 봤네요. 웹소켓 플러그인은 쓰면 쓸수록 좋은 것 같습니다! 항상 노고에 감사드립니다!!

**Comment by zcube** [comment]
빌드 및 배포를 AppVeyor로 옮겼더니 드랍박스로 올릴 방법이 없어 latest 링크는 제거했습니다.
게임을 하지 않는지라 간단한 수정 정도만 하고 있습니다.
